In [3]:
import h5py
import numpy as np

## 1. Basic elements

### 1.1. Comments and variables

In [4]:
#   here are some comments
a = 1  # a is a constant i use
b = 1.2  # float 
c = "this is a string"

In [5]:
# Casting and data types
indx = 2.0
A = [1, 2, 3]
print("one of the A's elements = ", A[int(indx)])
print(a, b)

one of the A's elements =  3
1 1.2


In [6]:
c = int(5.0)
d = float(a)
print(a, b, c, d)

z = 1.0+2.0j
print("1/2 = ", 1/2, 1/float(2), 1/2.0)

1 1.2 5 1.0
1/2 =  0.5 0.5 0.5


In [7]:
# Escape characters examples 
print("=====\"======\n====\t===")

====="======
====	===


In [8]:
# Some fun with strings and data type conversion
a = "HF energy is = -0.5Ha"
print(a)
print(a.upper())
print(a.lower())

A = a.split()
print(A)


E = A[4][0:4]
print(E)

print("hello" * 10)
print("The energy for 2 molecules will be = ", 2*int( float(E) ) )

print( int(1.99))

HF energy is = -0.5Ha
HF ENERGY IS = -0.5HA
hf energy is = -0.5ha
['HF', 'energy', 'is', '=', '-0.5Ha']
-0.5
hellohellohellohellohellohellohellohellohellohello
The energy for 2 molecules will be =  0
1


### 1.2. Dictionaries and lists

In [9]:
# Dictionaries
d = { "key":"value", "my_name":"Alexey", "my_age":35, "the_number_of_cats_i_have":0.0 }
d["my_age"], d["my_name"] = 40.0, "Nic"
#print( d )
d.update({"my_name":"Nicolas", "my_age":60})
#print( d )

In [10]:
my_cart = {}
my_cart_list = []
item1 = { "food":"meat", "cost":7.0 };     my_cart_list.append(item1); my_cart["item1"] = item1
item2 = { "food":"milk", "cost":3.0 };     my_cart_list.append(item2); my_cart.update( {"item2": item2} )
item3 = { "food":"tortilla", "cost":2.0 }; my_cart_list.append(item3); my_cart["item3"] = item3

#print(my_cart)
#print(my_cart_list)

In [11]:
# A list
my_list_1 = [ 1, 2, 3, 4]
my_list_2 = [ 1.0, 2.0, 3.0]
my_list_3 = ["a", "b", "c"]
my_list_4 = [1, "a", 1.02]

list_2D = [ [1.0, 2.0], [-2.0, 1.0] ]
#print( my_list_4[1] )
print(list_2D)
print(list_2D[0][1])

[[1.0, 2.0], [-2.0, 1.0]]
2.0


### 1.3. Printing and formatted printing

In [12]:
i, j = 0, 1
val = list_2D[i][j]
print("Printing element %i %i of my 2D list, the value is %5.3f" % (i, j, val) )

pi = 3.1415926
print("Printing pi = %5.2f" % (pi) )
print(F"Printing pi = {pi}")

pi = 3.1415926
print("Here is pi = {0:<10.2f}Here is the end".format(pi))
print("Here is pi = {0:<10.2f}Here is the end{1:+E}".format(pi, -pi))

Printing element 0 1 of my 2D list, the value is 2.000
Printing pi =  3.14
Printing pi = 3.1415926
Here is pi = 3.14      Here is the end
Here is pi = 3.14      Here is the end-3.141593E+00


### 1.4. Reading-writing files

In [13]:
f = open("data.txt", "a")
f.write("Printing pi = %5.2f\n" % (pi))
f.write(F"Printing pi = {pi}\n")
f.close()

f = open("data.txt", "r")
my_file_content = f.readlines()
f.close()

print(my_file_content)

#print(a, b, c, d)
#print(my_list_1, my_list_2, my_list_3, my_list_4)

['Printing pi =  3.14\n', 'Printing pi = 3.1415926\n']


## 1.5. Advanced: HDF5 files

In [14]:
def create():
    with h5py.File("myfile.dat", "w") as f:
        g = f.create_group("my_data")
        g.create_dataset("data", data = np.array([1,2,3], dtype=int))

def read():
    with h5py.File("myfile.dat", "r") as f:
        print(f["my_data/data"][:])

In [15]:
create()
read()

[1 2 3]


In [16]:
def create2():
    with h5py.File("myfile.hdf5", "w") as f:
        g = f.create_group("my_data")
        bg1 = g.create_group("exp")
        bg2 = g.create_group("theo")
        bg1.create_dataset("data", data = np.array([[1,2,3], [0.1, 0.2, 0.3]], dtype=float), compression="gzip")
        bg2.create_dataset("data", data = np.array([[-1,-2,-3], [-0.1, -0.2, -0.3]], dtype=float), compression="gzip")


def read2():
    with h5py.File("myfile.hdf5", "r") as f:
        x = f["my_data/exp/data"][0, :]
        print(x)
        y = f["my_data/theo/data"][0, :]
        print(y)


create2()
read2()

[1. 2. 3.]
[-1. -2. -3.]


# 2. Flow control

## 2.1. If - else

Conditions - a Boolean variable

In [17]:
#======== IF ELSE ======
a = "B"
b =     ( a == "A" )
print(b)
print(a == "A")

False
False


In [18]:
x = -1
if(x < 1):
    print("x < 1")
else:
    print("x >= 1")

x = 2
if(x<1):
    print("x < 1")
else:
    print("x >= 1")

x < 1
x >= 1


In [19]:
if(0):
    print("x < 1")
else:
    print("x >= 1")

x >= 1


In [20]:
a = "Abrr"
if(a == "A"):
    print("A")
elif(a == "B"):
    print("B")
elif(a == "C" or a == "Abrr"):
    print("C")
else:
    print("something else")



C


## 2.2. For and while loops

In [21]:
#======== FOR ======
for a in [1, 2, 3, "hi", "class"]:
    print(a)

1
2
3
hi
class


Can be nested - indentation is the key

In [22]:
for a in range(5,10):
    for b in range(3,6):
        print(a, b)

5 3
5 4
5 5
6 3
6 4
6 5
7 3
7 4
7 5
8 3
8 4
8 5
9 3
9 4
9 5


For the "while" loop - make sure to explicitly advance the state, to not fall into an infinite loop

In [23]:
#======= WHILE ========
x, counter = 0.0, 0
while(x < 20 and counter<10):
    print(x)
    x = x + 0.1
    counter += 1  #  counter = counter + 1

0.0
0.1
0.2
0.30000000000000004
0.4
0.5
0.6
0.7
0.7999999999999999
0.8999999999999999


## 3. Functions

### 3.1. Definitions

In [24]:
#========== FUNCTIONS =============
def my_pow(x, n):
    """
    Computes x^n , for non-negative n values 
    """

    res = x**n

    return res 


my_res = my_pow(0.0, 3); print(my_res)  # 0.0
my_res = my_pow(5.0, 0); print(my_res)  # 1.0
my_res = my_pow(5.0, 3); print(my_res)  # 125.0

0.0
1.0
125.0


## Exercise 1

Write a code to compute $$A x^n$$ using either `for` or `while` loops

Pass all the parameters as a dictionary.

## Exercise 2

Write a code to compute `exp(x)` function using Taylor series:

$$exp(x) \approx 1 + x + \frac{x^2}{2!} + \frac{x^3}{3!} + ... + \frac{x^n}{n!}$$

### 3.2. Functions as arguments

In [25]:
def my_derivative(func, x, n):
    
    dx = 0.001
    df = func(x+dx, n) - func(x-dx, n)
    deriv = df / (2.0*dx)
    
    return deriv

res = my_derivative(my_pow, 0.0, 3); print(res) # ( x^3 )'  at x=  0
res = my_derivative(my_pow, 5.0, 0); print(res) # ( x^0 )'  at x=  5
res = my_derivative(my_pow, 5.0, 3); print(res) # ( x^3 )'  at x=  5

1e-06
0.0
75.0000010000278


## Homework 1

Write a function to compute a definite integral of an aribtrary function (also taking an arbitrary number of  parameters) on a given interval according to one of the known quadrature rules, such as Simpson rule: https://en.wikipedia.org/wiki/Simpson%27s_rule. 

The more general the function (e.g. for functions of multiple dimensions), the better. 

Don't use the known solutions - write your own code. Never plagiarize.

Test it (e.g. see below)

## 4. Classes 

In [26]:
class vector:
    """
    This is a class to represent a 2D vector

    Warning:
        You can add up objects of this class using the :func:`my_math.functions.sum_vectors` functions

    """

    def __init__(self, _x, _y):
        """
        Constructor of the 2D vector object

        Args:
            _X ( double ): x-component of a vector
            _y ( double ): y-component of a vector

        Returns:
            None: but an object is initialized
        """

        self.x = _x
        self.y = _y


    def print(self):
        """ 
        Prints out the x and y components of the vector

        Args:
            None:

        Returns:
            None: but outputs the component 

        Note:
            Here is some note about this function
        """
        print(self.x, self.y)


def sum_vectors(v1, v2):
    """
    This functions adds up two vectors

    Args:
        v1 (vector): first operand
        v2 (vector): second operand
 
    Returns:
        vector: sum of the two
    """
   
    return vector(v1.x + v2.x, v1.y + v2.y)


In [27]:
v1 = vector(1.0, 0.0)
v2 = vector(2.0, -1.0)
v1.print()
v2.print()

1.0 0.0
2.0 -1.0


In [28]:
v3 = sum_vectors(v1, v2)
v3.print()

3.0 -1.0


A better version of the above class

In [29]:
class vector2D:
    """
    This is a class to represent a 2D vector

    Warning:
        You can add up objects of this class using the :func:`my_math.functions.sum_vectors` functions

    """

    def __init__(self, _x, _y):
        """
        Constructor of the 2D vector object

        Args:
            _X ( double ): x-component of a vector
            _y ( double ): y-component of a vector

        Returns:
            None: but an object is initialized
        """

        self.x = _x
        self.y = _y
        


    def print(self):
        """ 
        Prints out the x and y components of the vector

        Args:
            None:

        Returns:
            None: but outputs the component 

        Note:
            Here is some note about this function
        """
        print(self.x, self.y)
        
        
    def __add__(self, v):
        """ 
        Prints out the x and y components of the vector

        Args:
            None:

        Returns:
            None: but outputs the component 

        Note:
            Here is some note about this function
        """
        
        res = vector2D(0.0, 0.0)
        res.x = self.x + v.x
        res.y = self.y + v.y
        return res
        

In [30]:
v1 = vector2D(1.0, 0.0)
v2 = vector2D(2.0, -1.0)
v1.print()
v2.print()

1.0 0.0
2.0 -1.0


In [31]:
v3 = v1 + v2
v3.print()

3.0 -1.0


## Caution - assignment by references

In [32]:
v1 = vector2D(1, 1)
v2 = v1 
v2.print()

1 1


In [33]:
v1.x, v1.y = 2, 2

In [34]:
v2.print()

2 2


### Correct way is to use constructors 

But there is no overloading (same method name but with different number and type of arguments)in Python, so we can use `deepcopy` instead

In [36]:
import copy

v1 = vector2D(1, 1)
v2 = copy.deepcopy(v1)
v1.x, v1.y = 2, 2
v2.print()

1 1


Same for lists

In [37]:
list_A = [1, 1, 1]
list_B = list_A
print(list_B)

[1, 1, 1]


In [38]:
list_A[0] = 2
list_A[1] = 2
list_A[2] = 2

print(list_B)

[2, 2, 2]


but

In [39]:
list_A = [1, 1, 1]
list_B = list(list_A)
print(list_B)

list_A[0] = 2
list_A[1] = 2
list_A[2] = 2

print(list_B)

[1, 1, 1]
[1, 1, 1]


## 5. Testing

In [43]:
import unittest

class Test_vector2D(unittest.TestCase):

    def test_1(self):
        """Test constructors"""
        
        v = vector2D(0, 1)
        
        self.assertEqual(v.x, 0)
        self.assertEqual(v.y, 1)

    def test_2(self):
        """Test additions"""
        
        v1 = vector2D(0, 1) 
        v2 = vector2D(-1, 1) 
        v3 = v1 + v2
        
        self.assertAlmostEqual( v3.x, -1.0 )
        self.assertAlmostEqual( v3.y, 2.0 )
        
    def test_3(self):
        """Test additions, another one"""
        
        v1 = vector2D(1, 3) 
        v2 = vector2D(-2, -1) 
        v3 = v1 + v2
        
        self.assertAlmostEqual( v3.x, -1.0 )
        self.assertAlmostEqual( v3.y, 2.0 )
        
        
unittest.main(argv=[''], verbosity=2, exit=False)


test_1 (__main__.Test_vector2D)
Test constructors ... ok
test_2 (__main__.Test_vector2D)
Test additions ... ok
test_3 (__main__.Test_vector2D)
Test additions, another one ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.007s

OK
